cabal-version: 2.2
name: ghc-worker
version: 0.1
synopsis: GHC persistent worker through gRPC connection
license: MIT
license-file: LICENSE
build-type: Simple

flag mwb
    description: use mwb-customized GHC
    manual: True
    default: False

flag mwb-25-07
    description: use mwb-customized GHC from July 2025
    manual: True
    default: False

flag mwb-25-10
    description: use mwb-customized GHC from October 2025
    manual: True
    default: False

flag mwb-26-01
    description: Use mwb-customized GHC from January 2026
    manual: True
    default: False

flag unit-index
    description: Convenience flag for temporary changes made in an environment-injected local GHC
    manual: True
    default: False

common all
  ghc-options: -Wall -Widentities -Wincomplete-uni-patterns -Wmissing-deriving-strategies -Wredundant-constraints -Wunused-type-patterns -Wunused-packages
  default-language: GHC2021
  default-extensions:
    BlockArguments,
    DataKinds,
    DerivingStrategies,
    DuplicateRecordFields,
    LambdaCase,
    NamedFieldPuns,
    OverloadedLists,
    OverloadedRecordDot,
    OverloadedStrings,
    RecordWildCards,
    StrictData,
    TypeFamilies
  build-depends:
    base ==4.*

  if (flag(mwb))
      cpp-options: -DMWB

  if (flag(mwb-25-07))
      cpp-options: -DMWB -DMWB_2025_07

  if (flag(mwb-25-10))
      cpp-options: -DMWB -DMWB_2025_10

  if (flag(mwb-26-01))
      cpp-options: -DMWB -DMWB_2026_01

  if (flag(unit-index))
      cpp-options: -DUNIT_INDEX

library
  import: all
  ghc-options: -O2
  hs-source-dirs: lib
  exposed-modules:
    GhcWorker.CompileResult
    GhcWorker.GhcHandler
    GhcWorker.Grpc
    GhcWorker.Instrumentation
    GhcWorker.Orchestration
    GhcWorker.Run
  build-depends:
    async,
    binary,
    buck-worker-grpc,
    buck-worker-internal,
    buck-worker-proto,
    buck-worker-types,
    bytestring,
    containers,
    deepseq,
    directory,
    filepath,
    ghc,
    ghc-debug-stub,
    grapesy ^>=1.0.1,
    process,
    text

executable ghc-worker
  import: all
  main-is: Main.hs
  hs-source-dirs: app/ghc-worker
  ghc-options: -O2 -threaded "-with-rtsopts=-K512M -I5 -A128M -T -N"
  build-depends:
    ghc-worker

test-suite worker-test
  import: all
  type: exitcode-stdio-1.0
  main-is: Main.hs
  hs-source-dirs: test
  other-modules:
    CompileHptTest,
    TestSetup,
    UnitIndexTest
  ghc-options: -threaded -rtsopts "-with-rtsopts=-N -T"
  build-depends:
    buck-worker-internal,
    buck-worker-types,
    containers,
    directory,
    filepath,
    ghc,
    temporary,
    text,
    transformers,
    typed-process
